#set_false_path -to [get_pins -hier -filter {NAME =~ {*/inst/type_loop[*].inst_loop[*].dpram_i/memory_reg/WEBWE[*]}}]
#set_false_path -to [get_pins -hier -filter {NAME =~ {*/inst/type_loop[*].inst_loop[*].dpram_i/memory_reg/ENBWREN}}]


set_false_path -from [get_nets -hierarchical -filter {NAME =~ {*/flexDMA_ram_*/TYPE0_EN[*]}}]
set_false_path -from [get_nets -hierarchical -filter {NAME =~ {*/flexDMA_ram_*/TYPE1_EN[*]}}]
set_false_path -from [get_nets -hierarchical -filter {NAME =~ {*/flexDMA_ram_*/TYPE2_EN[*]}}]
set_false_path -from [get_nets -hierarchical -filter {NAME =~ {*/flexDMA_ram_*/TYPE3_EN[*]}}]
set_false_path -from [get_nets -hierarchical -filter {NAME =~ {*/flexDMA_ram_*/TYPE4_EN[*]}}]
set_false_path -from [get_nets -hierarchical -filter {NAME =~ {*/flexDMA_ram_*/TYPE5_EN[*]}}]
set_false_path -from [get_nets -hierarchical -filter {NAME =~ {*/flexDMA_ram_*/TYPE6_EN[*]}}]
set_false_path -from [get_nets -hierarchical -filter {NAME =~ {*/flexDMA_ram_*/TYPE7_EN[*]}}]
set_false_path -from [get_nets -hierarchical -filter {NAME =~ {*/flexDMA_ram_*/TYPE8_EN[*]}}]
set_false_path -from [get_nets -hierarchical -filter {NAME =~ {*/flexDMA_ram_*/TYPE9_EN[*]}}]
set_false_path -from [get_nets -hierarchical -filter {NAME =~ {*/flexDMA_ram_*/TYPE10_EN[*]}}]
set_false_path -from [get_nets -hierarchical -filter {NAME =~ {*/flexDMA_ram_*/TYPE11_EN[*]}}]
set_false_path -from [get_nets -hierarchical -filter {NAME =~ {*/flexDMA_ram_*/TYPE12_EN[*]}}]
set_false_path -from [get_nets -hierarchical -filter {NAME =~ {*/flexDMA_ram_*/TYPE13_EN[*]}}]
set_false_path -from [get_nets -hierarchical -filter {NAME =~ {*/flexDMA_ram_*/TYPE14_EN[*]}}]
set_false_path -from [get_nets -hierarchical -filter {NAME =~ {*/flexDMA_ram_*/TYPE15_EN[*]}}]
set_false_path -from [get_nets -hierarchical -filter {NAME =~ {*/flexDMA_ram_*/TYPE16_EN[*]}}]
set_false_path -from [get_nets -hierarchical -filter {NAME =~ {*/flexDMA_ram_*/TYPE17_EN[*]}}]
set_false_path -from [get_nets -hierarchical -filter {NAME =~ {*/flexDMA_ram_*/TYPE18_EN[*]}}]